name: Deploy Sphinx Docs to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Ensure your requirements.txt includes Sphinx and other dependencies
        pip install sphinx sphinx-rtd-theme  # Example of installing a Sphinx theme

    - name: Verify Makefile
      run: |
        cd sphinx  # Change to your docs directory if needed
        if [ ! -f Makefile ]; then
          echo "Makefile not found! Generating Makefile using sphinx-quickstart."
          sphinx-quickstart --sep -p "Project Name" -a "Author" -v "1.0" --makefile --batchfile
        fi

    - name: Build documentation
      run: |
        cd sphinx  # Change to your docs directory if needed
        make html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages  # Ensure this matches the branch configured in GitHub Pages settings
        publish_dir: ./sphinx/build/html  # Adjust this path to where your HTML files are generated
