name: Python application + FIX Demo

on: [workflow_dispatch]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -U
        pip install pytest pytest-timeout pytest-asyncio flake8

    - name: Download FIX44 spec
      run: |
        curl https://raw.githubusercontent.com/quickfix/quickfix/master/spec/FIX44.xml -o FIX44.xml

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run tests
      run: pytest -s --spec=FIX44.xml --timeout=90 -v

    - name: Install this package
      run: |
        pip install . --force-reinstall --no-cache-dir

    - name: Run FIX Acceptor in background
      run: |
        python examples/cli_acceptor.py > acceptor_logs.txt 2>&1 &
        echo $! > acceptor_pid.txt
        sleep 5  # Give the acceptor time to start

    # - name: Telnet test to verify connection
    #   run: |
    #     # sudo apt-get update && sudo apt-get install -y telnet
    #     telnet 127.0.0.1 5000 || echo "Telnet test failed"

    # - name: Run FIX Initiator Demo
    #   run: |
    #     python examples/cli_initiator.py > initiator_logs.txt 2>&1 &
    #     INITIATOR_PID=$!
    #     sleep 60
    #     kill $INITIATOR_PID || true
    - name: Run FIX Initiator Demo
      run: |
        echo "--- Contents of pyfixmsg/__init__.py before initiator run ---"
        cat pyfixmsg/__init__.py  # Or the correct relative path from $PWD
        echo "--- End of pyfixmsg/__init__.py contents ---"
        PYTHONPATH=$PWD python examples/cli_initiator.py > initiator_logs.txt 2>&1 &
        INITIATOR_PID=$!
        sleep 60 # Keep this to allow the script to run and log
        kill $INITIATOR_PID || true
    # - name: Run FIX Initiator Demo
    #   run: |
    #     PYTHONPATH=$PWD python examples/cli_initiator.py > initiator_logs.txt 2>&1 &
    #     INITIATOR_PID=$!
    #     sleep 60
    #     kill $INITIATOR_PID || true
        
    - name: Stop Acceptor
      run: |
        kill $(cat acceptor_pid.txt) || true

    - name: Show Acceptor FIX Messages
      run: |
        cat acceptor_logs.txt || echo "No logs found for acceptor."

    - name: Show Initiator FIX Messages
      run: |
        cat initiator_logs.txt || echo "No logs found for initiator."
